# Generated by Django 5.2.8 on 2025-11-06 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('store', '0002_alter_category_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم السداد'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='store.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='تم الدفع بنجاح'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'بطاقة ائتمانية'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدًا')], max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='store.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
